trainer: conv
out_dir: ../tmp_out  # NOTE: specify a directory in your scratch directory on Leonhard

device: cpu

model:
  name: pre_trained

training:
  print_every: 100
  validate_every: 5000
  checkpoint_every: 5000

  optimizer:
#    name: SGD
#    lr: 0.0001
    name: ADAM
    lr: 0.0001

  batch_size: 32
  num_workers: 4

loss:
  v2v_l1: True  # loss type
  v2v_l1_w: 1.0  # corresponding weight

  v2v_l2: True
  v2v_l2_w: 1.0

#  j2j_l1: True
#  j2j_l1_w: 1.0
#
#  j2j_l2: True
#  j2j_l2_w: 1.0

  RL_l1: True
  RL_l1_w: 1.0

#  RL_l2: True
#  RL_l2_w: 1.0


data:
  dataset: base  # dataset type
  resy: 256
  resx: 256
  train_subjects: S1
  val_subjects: S1  # you could use this subjects for training as well

  # there is no need to modify the following parameters on Leonhard
  dataset_folder: ../../data/H36M_data_st
  img_folder: ../../data/H36M
  bm_path: ../../body_model/model.npz
