trainer: conv
out_dir: C:/Users/Severin/Data/mp_project/outdir  # NOTE: specify a directory in your scratch directory on Leonhard

device: cuda

model:
  name: hmr_pre

training:
  print_every: 200
  validate_every: 1000
  checkpoint_every: 10000


  optimizer:
    # name: SGD
    # lr: 0.0001
    name: ADAM
    lr: 0.0001

  batch_size: 12
  num_workers: 8

loss:
  v2v_l1: True  # loss type
  v2v_l1_w: 0.0  # corresponding weight

  v2v_l2: True
  v2v_l2_w: 1.0

  j2j_l1: False
  j2j_l1_w: 1.0

  j2j_l2: True
  j2j_l2_w: 5.0

  p2p_l1: False
  p2p_l1_w: 1.0

  p2p_l2: False
  p2p_l2_w: 1.0

  r2r_l2: False
  r2r_l2_w: 0.5

  b2b_l2: True
  b2b_l2_w: 0.2

  RL_l1: False
  RL_l1_w: 0.1

  chamfer_loss: False
  chamfer_loss_w: 1.0

#  RL_l2: True
#  RL_l2_w: 1.0

data:
  dataset: base  # dataset type
  resy: 256
  resx: 256
  train_subjects: S1,S5,S6,S7
  val_subjects: S8  # you could use this subjects for training as well

  downsample: True
  ds_ratio: 0.2  # take every 5th value

  # there is no need to modify the following parameters on Leonhard
  dataset_folder: C:/Users/Severin/Data/mp_project/data/H36M_data_st
  img_folder: C:/Users/Severin/Data/mp_project/data/H36M
  bm_path: C:/Users/Severin/Data/mp_project/body_model/model.npz