trainer: conv
out_dir: ../tmp_out  # NOTE: specify a directory in your scratch directory on Leonhard

device: cuda

model:
  name: pre_trained_reg # conv, pre_trained_reg

training:
  print_every: 10      # 50
  validate_every: 256 # 267   # S1:4963  # w/b32 -> end of epoch 2 3100
  checkpoint_every: 0    # 5000

  optimizer:
    name: SGD # SGD, ADAM
    lr: 0.0001
  swa: True

  batch_size: 12  # 10
  num_workers: 3

loss:
  v2v_l1: True   # loss type
  v2v_l1_w: 1.0  # corresponding weight

  v2v_l2: True
  v2v_l2_w: 1.0

data:
  dataset: base  # dataset type
  resy: 256 # 256
  resx: 256 # 256
  train_subjects: S1,S7 #S1 S5,S6
  val_subjects: S8   # S6 S7,S8  # TODO:you could use this subjects for training as well
  downsample: True
  ds_ratio: 0.06  # take every 5th value

  # there is no need to modify the following parameters on Leonhard
  dataset_folder: e:/Datasets/project3/data/H36M_data_st # c:/Dataset/data/H36M_data_st  # /cluster/project/infk/hilliges/lectures/mp21/project3/data/H36M_data_st
  img_folder: e:/Datasets/project3/data/H36M     # c:/Dataset/data/H36M              # /cluster/project/infk/hilliges/lectures/mp21/project3/data/H36M
  bm_path: e:/Datasets/project3/body_model/model.npz # c:/Dataset/body_model/model.npz      # /cluster/project/infk/hilliges/lectures/mp21/project3/body_model/model.npz