trainer: hmr #conv
out_dir: ../tmp_out # NOTE: specify a directory in your scratch directory on Leonhard

device: cuda
# device: cpu

model:
  name: pre_trained # conv

training:
  print_every: 100
  validate_every: 0 # 5000
  checkpoint_every: 4000 # 5000

  optimizer:
    # name: SGD
    # lr: 0.0001
    name: ADAM # generator optimizer
    lr: 0.0001

    name1: ADAM # discriminator optimizer
    lr1: 0.001

  batch_size: 20
  num_workers: 4

loss:
  v2v_l1: True # loss type
  v2v_l1_w: 7.0 # corresponding weight

  v2v_l2: True
  v2v_l2_w: 15.0

  kp_3d_l2: True # 3D joint position loss L2
  kp_3d_l2_w: 4.0

  shape_l2: True
  shape_l2_w: 0.01

  pose_l2: True
  pose_l2_w: 2.0

  gen_disc_l2: True # Adversarial loss function for encoder/generator
  gen_disc_l2_w: 2

  disc_loss: True
  disc_loss_w: 1

data:
  dataset: base # dataset type
  resy: 256 # 256
  resx: 256 # 256
  train_subjects: S1,S5,S6,S7,S8
  val_subjects: S8  # TODO:you could use this subjects for training as well
  downsample: True
  ds_ratio: 0.2 # 0.2 # take every 5th value

  # there is no need to modify the following parameters on Leonhard
  dataset_folder: /cluster/project/infk/hilliges/lectures/mp21/project3/data/H36M_data_st
  img_folder: /cluster/project/infk/hilliges/lectures/mp21/project3/data/H36M
  bm_path: /cluster/project/infk/hilliges/lectures/mp21/project3/body_model/model.npz

  # dataset_folder: /home/henry/Documents/ETH_MA/MachinePerception/project3/H36M_data_st
  # img_folder: /home/henry/Documents/ETH_MA/MachinePerception/project3/H36M
  # bm_path: /home/henry/Documents/ETH_MA/MachinePerception/project3/body_model/model.npz

  # img_folder: D:\Bibliothek\MP\project3\data\H36M
  # dataset_folder: D:\Bibliothek\MP\project3\data\H36M_data_st
  # bm_path: D:\Bibliothek\MP\project3\body_model\model.npz
